baseURL = "https://androiddevcoding.github.io/"
languageCode = "ru-ru"
title = "Developer Notes"
theme = "PaperMod"
publishDir = "docs"

[pagination]
  pagerSize = 10
  
[params]
  defaultTheme = "auto"
  disableSpecial1stPost = true

[params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"

[markup.goldmark.renderer]
  unsafe = true

[menu]
    [[menu.main]]
    identifier = "home"
    name = "Главная"
    url = "/"
    weight = 1

    [[menu.main]]
    identifier = "projects"
    name = "Проекты"
    url = "/projects/"
    weight = 2

    [[menu.main]]
    identifier = "about"
    name = "Обо мне"
    url = "/about/"
    weight = 3
